services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgres/data
  web:
    build: .
    command: |
      bash -c "
      bundle install &&
      bin/rails s -b 0.0.0.0
      "
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
volumes:
  db-data:
