databases:
  - name: zero_steps_db
    databaseName: zero_steps_db
    user: zero_steps
    region: singapore

services:
  - type: web
    name: zero_steps
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zero_steps_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
